### ISSUE TITLE
Dev server create not wanted file

### ISSUE THREAD

**Issue by Horsty80** [JohnBra/vite-web-extension#6] opened 2022-10-05 21:36 UTC
Nice template =)

Exactly what i want.
I try to use it, but that is a strange behavior when dev server is running.

If you update vite.config.js that create a temporary file like this `vite.config.ts.timestamp-1665005464976.js`

# How to reproduce
- npm run dev
- make changes inside `vite.config.js`
- after the reload on dev server, you have a timestamped file at the root of the app.

**Comment by JohnBra** [comment] 2022-10-06 09:51
Hi Horsty80! Glas you find it helpful :)

Thanks for opening this issue.

To your issue: I'm using yarn, which is why there is a `yarn.lock` file on the root level. Have you tried to run it with yarn? I don't seem to get this issue

**Comment by Horsty80** [comment] 2022-10-06 10:58
Very annoying issue ^^'

<img width="503" alt="Capture d’écran 2022-10-06 à 12 57 53" src="https://user-images.githubusercontent.com/15615569/194296211-a866e905-9ad1-42be-9ffb-bbb4d678a467.png">

**Comment by Horsty80** [comment] 2022-10-06 11:06
After some test with `yarn`/ `npm`/`pnpm`
i have the same issue.

To reproduce easily :
- open `vite.confing.ts`
- save the file multiple times (in my case `cmd` + `s`) and see multiple file created

**Comment by Horsty80** [comment] 2022-10-06 11:14
> After some test with `yarn`/ `npm`/`pnpm` i have the same issue.
> 
> To reproduce easily :
> 
> * open `vite.confing.ts`
> * save the file multiple times (in my case `cmd` + `s`) and see multiple file created

Spaming saving on any watched files lead to the same issue

I really think it's a nodemon issue

**Comment by JohnBra** [comment] 2022-10-07 04:32
@Horsty80 I agree, this seems to be a `nodemon` issue.

I just tried to reproduce it in 2 of my extensions: no luck

So, I went ahead did this:
1. Create a new repo from this template
2. Clone the repo
3. `yarn install`
4. `yarn dev`
5. Modified the `vite.config.ts` file (deleted some inputs from rollup)

Still no luck: everything works as it should

I also just realized you wrote `vite.config.js` in one of your earlier issues, but it's supposed to be `vite.config.ts` (note the `ts`). It seems like you are having issues with file extensions here. Could be the `nodemon` can't fetch a delta there and just creates a new file for every change.

Could you look into the file extension on your end?

**Comment by Horsty80** [comment] 2022-10-07 08:00
@JohnBra thanks.

To reproduce you need only one thing : spamming your save shortcut on any file 

I will try from this template scratch and keep you in touch for the result.
And i have `vite.config.ts` the `.js` file is the generated files (so is the result of the transpile of TS to JS file for the build)

**Comment by Horsty80** [comment] 2022-10-07 10:49
@JohnBra i have test with your repo and I reproduce

I attach video of the manip 

[Enregistrement de l’écran 2022-10-07 à 12.46.50.mov.zip](https://github.com/JohnBra/vite-web-extension/files/9733243/Enregistrement.de.l.ecran.2022-10-07.a.12.46.50.mov.zip)

I think is due to fastest save, I'm working with a MacBook Pro M1 Max so maybe it's

**Comment by JohnBra** [comment] 2022-10-07 21:15
Hmm, I see.

I wish I could fix it, but since I can't seem to reproduce it it's not really possible to do anything from my side :/

After a quick google to see if others had a similar problem I also couldn't find anything..

Could you try it on a different machine?

**Comment by Horsty80** [comment] 2022-10-07 21:24
Yes no similar issue I google it before open this issue ^^'

I deal with it, but is't inconvenient.
And I want to no why I have this issue

**Comment by JohnBra** [comment] 2022-10-07 21:31
Understandable.

I'm going to close this issue, as there is nothing I can do.

If you find out how to fix it, I would be interested to know :) You can either let me know here, or via Twitter DM. You can find my socials in my Github profile: https://github.com/JohnBra

**Comment by Horsty80** [comment] 2022-10-07 21:32
Yes sure thank for your time

**Closed by JohnBra** 2022-10-07 21:31 UTC

**Comment by Horsty80** [comment] 2022-10-25 22:29
I simply resolve my issue by remove nodemon and only use viteJs and specifically rollup configuration

I'm using the build-watch config 

https://vitejs.dev/config/build-options.html#build-watch


```js

    build: {
      watch: {
        include: "src/**",
      },
      sourcemap: false,
      rollupOptions: {
        input: {
          background: resolve(pagesDir, "background", "index.ts"),
          popup: resolve(pagesDir, "popup", "index.html"),
        },
        output: {
          entryFileNames: (chunk) => `src/pages/${chunk.name}/index.js`,
        },
      },
    },
```

it's working fine you can adjust the delay see rollup doc https://rollupjs.org/guide/en/#watch-options

I can remove dependency of nodemon like this way :)
To simplify I have now 2 command :
- pnpm build:dev:chrome <- this is with watch config
- pnpm build:chrome <- this is without watch config

**Comment by JohnBra** [comment] 2022-10-26 05:23
That's good to know!
Glad you could solve it on your end and thanks for letting me know!

Might come in handy
