### ISSUE TITLE
Refused to load script

### ISSUE THREAD

**Issue by huzaifa-bilal-01** [JohnBra/vite-web-extension#40] opened 2024-10-23 06:09 UTC
Getting this error when ever loading the extension:

"Refused to load the script 'chrome-extension://a5359a9d-e2f9-46a3-a0e5-0911e6083ec5/assets/index.tsx-B39MazF-.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."

**Comment by JohnBra** [comment] 2024-10-23 19:04
Hi @huzaifa-bilal-01, thanks for opening the issue.

Could you please provide more information on your system and what steps you have already taken to fix the problem?

**Describe the bug**
A clear and concise description of what the bug is.


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Steps/attempts taken to fix**
Add the steps you have attempted to fix your problem here.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS] including version
 - Browser [e.g. chrome, firefox] including version

**Comment by dtszwai** [comment] 2024-10-23 20:41
I had the same issue yesterday. After upgrading Chrome, the problem was resolved.
My current Chrome version is: Version 130.0.6723.70 (Official Build) (arm64).

**Comment by huzaifa-bilal-01** [comment] 2024-10-24 04:36
> I had the same issue yesterday. After upgrading Chrome, the problem was resolved. My current Chrome version is: Version 130.0.6723.70 (Official Build) (arm64).

**Chrome is up to date
Version 130.0.6723.70 (Official Build) (64-bit)**

My chrome is up to date but still getting the same error.

**Comment by huzaifa-bilal-01** [comment] 2024-10-24 05:21
> Hi @huzaifa-bilal-01, thanks for opening the issue.
> 
> Could you please provide more information on your system and what steps you have already taken to fix the problem?
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Steps/attempts taken to fix** Add the steps you have attempted to fix your problem here.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows, Linux, MacOS] including version
> * Browser [e.g. chrome, firefox] including version

Thanks for your response! Below is the information related to the issue I encountered:

**BUG:**
When loading extension, I receive the following error message in the console:
![image](https://github.com/user-attachments/assets/46967c3a-3dac-4c0a-a541-8f617cda5e6f)

_It seems like the extension is blocked from loading its own script due to the CSP settings._

**TO REPRODUCE:**
Steps to reproduce the issue:

1. Install the extension locally.
2. Load the extension in Chrome.
3. Open the browser console.
4. Reload the page where the extension is active.
5. See the CSP error in the console.

**EXPECTED BEHAVIOUR:**
I expect the extension to load its own script (content script) without being blocked by the CSP, allowing it to function correctly.

**DESKTOP:**
OS: Windows 10, Windows 11 
Browser: Chrome (Version 130.0.6723.70), Edge (Version 130.0.2849.46), Brave (Version 130.1.71.118)

_**NOTE: It is working fine on the opera or opera gx browser.**_

**Comment by JohnBra** [comment] 2024-10-24 07:45
@huzaifa-bilal-01 Thanks for bringing this to my attention.

Looks like Chrome updated their CSP with a recent browser update.

Should be fixed within the most resent version of this template repository.

If you want to fix it in your project without creating a new project from this template, you will need to update the package `@crxjs/vite-plugin` from the current version to `@crxjs/vite-plugin@2.0.0-beta.26`.

Let me know if this works for you.

**Comment by huzaifa-bilal-01** [comment] 2024-10-24 08:04
> @huzaifa-bilal-01 Thanks for bringing this to my attention.
> 
> Looks like Chrome updated their CSP with a recent browser update.
> 
> Should be fixed within the most recent version of this template repository.
> 
> If you want to fix it in your project without creating a new project from this template, you will need to update the package `@crxjs/vite-plugin` from the current version to `@crxjs/vite-plugin@2.0.0-beta.26`.
> 
> Let me know if this works for you.

Yeps this worked. Thanks 👍

**Comment by JohnBra** [comment] 2024-10-24 08:13
Awesome!

Closing.

**Closed by JohnBra** 2024-10-24 08:13 UTC
